name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true  # Ensure LFS files are checked out

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Install missing libarchive system library for conda-libmamba-solver
    - name: Install missing system dependencies (libarchive)
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-dev

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yaml
        activate-environment: driver_acceptance_rate
        use-mamba: false  # Disable mamba to avoid libarchive issue

    - name: Install Node.js
      run: conda install -c conda-forge nodejs

    - name: Install CML
      run: npm install -g @dvcorg/cml

    - name: Run the pipeline (Makefile)
      run: make run

    - name: Post metrics to GitHub as a comment
      run: cml comment create report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
